--------------------------------------------------------
--  File created - Perþembe-Ocak-21-2021   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence CALISAN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."CALISAN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 61 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence OTOMAT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."OTOMAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence URUN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."URUN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence URUN_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."URUN_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence URUN_SEQ2
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."URUN_SEQ2"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence YONETICI_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."YONETICI_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence YONETICI_SEQ1
--------------------------------------------------------

   CREATE SEQUENCE  "HABIBOI"."YONETICI_SEQ1"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table CALISAN
--------------------------------------------------------

  CREATE TABLE "HABIBOI"."CALISAN" 
   (	"CALISAN_NO" VARCHAR2(20 BYTE), 
	"AD_SOYAD" VARCHAR2(20 BYTE), 
	"EKIP_NO" VARCHAR2(20 BYTE), 
	"MUSAITLIK" VARCHAR2(20 BYTE) DEFAULT 'Müsait', 
	"KULLANICI_ADI" VARCHAR2(20 BYTE), 
	"SIFRE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table OTOMAT
--------------------------------------------------------

  CREATE TABLE "HABIBOI"."OTOMAT" 
   (	"OTOMAT_NO" VARCHAR2(20 BYTE), 
	"IL" VARCHAR2(20 BYTE), 
	"ILCE" VARCHAR2(20 BYTE), 
	"MAHALLE" VARCHAR2(20 BYTE), 
	"SOKAK" VARCHAR2(20 BYTE), 
	"RAF_KAPASITESI" VARCHAR2(20 BYTE) DEFAULT '20', 
	"URUN_0" VARCHAR2(20 BYTE) DEFAULT 'Pringles', 
	"URUN_1" VARCHAR2(20 BYTE) DEFAULT 'Twix', 
	"URUN_2" VARCHAR2(20 BYTE) DEFAULT 'AOÇ Su', 
	"BAKIM" VARCHAR2(50 BYTE) DEFAULT 'Kayýt Yok'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table URUN
--------------------------------------------------------

  CREATE TABLE "HABIBOI"."URUN" 
   (	"URUN_NO" VARCHAR2(20 BYTE), 
	"URUN_AD" VARCHAR2(20 BYTE), 
	"FIYAT" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table YONETICI
--------------------------------------------------------

  CREATE TABLE "HABIBOI"."YONETICI" 
   (	"YONETICI_NO" VARCHAR2(20 BYTE), 
	"AD_SOYAD" VARCHAR2(20 BYTE), 
	"KULLANICI_ADI" VARCHAR2(20 BYTE), 
	"SIFRE" VARCHAR2(20 BYTE), 
	"BOLGE" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
REM INSERTING into HABIBOI.CALISAN
SET DEFINE OFF;
Insert into HABIBOI.CALISAN (CALISAN_NO,AD_SOYAD,EKIP_NO,MUSAITLIK,KULLANICI_ADI,SIFRE) values ('41','Sualp OKUR','1','Müsait','sualpi','123');
Insert into HABIBOI.CALISAN (CALISAN_NO,AD_SOYAD,EKIP_NO,MUSAITLIK,KULLANICI_ADI,SIFRE) values ('42','Oðulcan CEYLAN','1','Müsait','ociboss','123');
Insert into HABIBOI.CALISAN (CALISAN_NO,AD_SOYAD,EKIP_NO,MUSAITLIK,KULLANICI_ADI,SIFRE) values ('43','Cafer ÖZTÜRK','2','Müsait','cafocaf','111');
Insert into HABIBOI.CALISAN (CALISAN_NO,AD_SOYAD,EKIP_NO,MUSAITLIK,KULLANICI_ADI,SIFRE) values ('44','Alper BEÞPARMAK','2','Müsait','alperlol','111');
Insert into HABIBOI.CALISAN (CALISAN_NO,AD_SOYAD,EKIP_NO,MUSAITLIK,KULLANICI_ADI,SIFRE) values ('45','Mete Zorbey','2','Müsait','metebro32','111');
Insert into HABIBOI.CALISAN (CALISAN_NO,AD_SOYAD,EKIP_NO,MUSAITLIK,KULLANICI_ADI,SIFRE) values ('21','Onur SERÝN','1','Müsait','serinke','123');
REM INSERTING into HABIBOI.OTOMAT
SET DEFINE OFF;
Insert into HABIBOI.OTOMAT (OTOMAT_NO,IL,ILCE,MAHALLE,SOKAK,RAF_KAPASITESI,URUN_0,URUN_1,URUN_2,BAKIM) values ('1','Ankara','Çankaya','Anýttepe','GMK Bulvarý','20','Snickers','Twix','AOÇ Su','Ekip yola çýktý. 21.01.2021 03:09:34');
Insert into HABIBOI.OTOMAT (OTOMAT_NO,IL,ILCE,MAHALLE,SOKAK,RAF_KAPASITESI,URUN_0,URUN_1,URUN_2,BAKIM) values ('2','Ankara','Yenimahalle','25 Mart','Çaldýran Caddesi','25','Snickers','Twix','AOÇ Su','Ürünler Eklendi 21.01.2021 00:44');
Insert into HABIBOI.OTOMAT (OTOMAT_NO,IL,ILCE,MAHALLE,SOKAK,RAF_KAPASITESI,URUN_0,URUN_1,URUN_2,BAKIM) values ('3','Ankara','Çankaya','Gazi','Gümüþçü Sokak','20','Snickers','Twix','AOÇ Su','Ürünler Eklendi 21.01.2021 00:45');
REM INSERTING into HABIBOI.URUN
SET DEFINE OFF;
Insert into HABIBOI.URUN (URUN_NO,URUN_AD,FIYAT) values ('1','Twix','2');
Insert into HABIBOI.URUN (URUN_NO,URUN_AD,FIYAT) values ('2','Snickers','3');
Insert into HABIBOI.URUN (URUN_NO,URUN_AD,FIYAT) values ('3','AOÇ Su','1');
REM INSERTING into HABIBOI.YONETICI
SET DEFINE OFF;
Insert into HABIBOI.YONETICI (YONETICI_NO,AD_SOYAD,KULLANICI_ADI,SIFRE,BOLGE) values ('1','Habip ÞANA','habiboi','123','Çankaya');
Insert into HABIBOI.YONETICI (YONETICI_NO,AD_SOYAD,KULLANICI_ADI,SIFRE,BOLGE) values ('2','Berkay YILMAZ','berkayboi','123','Yenimahalle');
--------------------------------------------------------
--  DDL for Index EKIP_CALISANI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HABIBOI"."EKIP_CALISANI_PK" ON "HABIBOI"."CALISAN" ("CALISAN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index URUN_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HABIBOI"."URUN_PK" ON "HABIBOI"."URUN" ("URUN_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index OTOMAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HABIBOI"."OTOMAT_PK" ON "HABIBOI"."OTOMAT" ("OTOMAT_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index YONETICI_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "HABIBOI"."YONETICI_PK" ON "HABIBOI"."YONETICI" ("YONETICI_NO") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Trigger CALISAN_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HABIBOI"."CALISAN_TRG" 
BEFORE INSERT ON CALISAN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.CALISAN_NO IS NULL THEN
      SELECT CALISAN_SEQ.NEXTVAL INTO :NEW.CALISAN_NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HABIBOI"."CALISAN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger OTOMAT_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HABIBOI"."OTOMAT_TRG" 
BEFORE INSERT ON OTOMAT 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.OTOMAT_NO IS NULL THEN
      SELECT OTOMAT_SEQ.NEXTVAL INTO :NEW.OTOMAT_NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HABIBOI"."OTOMAT_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger URUN_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HABIBOI"."URUN_TRG" 
BEFORE INSERT ON URUN 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.URUN_NO IS NULL THEN
      SELECT URUN_SEQ2.NEXTVAL INTO :NEW.URUN_NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HABIBOI"."URUN_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Trigger YONETICI_TRG
--------------------------------------------------------

  CREATE OR REPLACE EDITIONABLE TRIGGER "HABIBOI"."YONETICI_TRG" 
BEFORE INSERT ON YONETICI 
FOR EACH ROW 
BEGIN
  <<COLUMN_SEQUENCES>>
  BEGIN
    IF INSERTING AND :NEW.YONETICI_NO IS NULL THEN
      SELECT YONETICI_SEQ1.NEXTVAL INTO :NEW.YONETICI_NO FROM SYS.DUAL;
    END IF;
  END COLUMN_SEQUENCES;
END;
/
ALTER TRIGGER "HABIBOI"."YONETICI_TRG" ENABLE;
--------------------------------------------------------
--  DDL for Procedure CALISAN_EKLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "HABIBOI"."CALISAN_EKLE" 
(
    P_AD            CALISAN.AD_SOYAD%TYPE,
    P_KULLANICI     CALISAN.KULLANICI_ADI%TYPE,
    P_EKIP          CALISAN.EKIP_NO%TYPE,
    P_SIFRE         CALISAN.SIFRE%TYPE
)
IS
BEGIN
  INSERT INTO CALISAN (AD_SOYAD,KULLANICI_ADI,EKIP_NO,SIFRE) VALUES (P_AD,P_KULLANICI,P_EKIP,P_SIFRE);
END CALISAN_EKLE;

/
--------------------------------------------------------
--  DDL for Procedure OTOMAT_EKLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "HABIBOI"."OTOMAT_EKLE" 
(
    P_IL            OTOMAT.IL%TYPE,
    P_ILCE          OTOMAT.ILCE%TYPE,
    P_MAHALLE       OTOMAT.MAHALLE%TYPE,
    P_SOKAK         OTOMAT.SOKAK%TYPE
)
IS
BEGIN
  INSERT INTO OTOMAT (IL,ILCE,MAHALLE,SOKAK) VALUES (P_IL,P_ILCE,P_MAHALLE,P_SOKAK);
END OTOMAT_EKLE;

/
--------------------------------------------------------
--  DDL for Procedure URUN_EKLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "HABIBOI"."URUN_EKLE" 
(
    P_AD    URUN.URUN_AD%TYPE,
    P_FIYAT URUN.FIYAT%TYPE
)
IS
BEGIN
  INSERT INTO URUN (URUN_AD,FIYAT) VALUES (P_AD,P_FIYAT);
END URUN_EKLE;

/
--------------------------------------------------------
--  DDL for Procedure YONETICI_EKLE
--------------------------------------------------------
set define off;

  CREATE OR REPLACE EDITIONABLE PROCEDURE "HABIBOI"."YONETICI_EKLE" 
(
    P_AD            YONETICI.AD_SOYAD%TYPE,
    P_KULLANICI     YONETICI.KULLANICI_ADI%TYPE,
    P_SIFRE         YONETICI.SIFRE%TYPE,
    P_BOLGE         YONETICI.BOLGE%TYPE
)
IS
BEGIN
  INSERT INTO YONETICI (AD_SOYAD,KULLANICI_ADI,SIFRE,BOLGE) VALUES (P_AD,P_KULLANICI,P_SIFRE,P_BOLGE);
END YONETICI_EKLE;

/
--------------------------------------------------------
--  Constraints for Table YONETICI
--------------------------------------------------------

  ALTER TABLE "HABIBOI"."YONETICI" MODIFY ("YONETICI_NO" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."YONETICI" MODIFY ("AD_SOYAD" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."YONETICI" MODIFY ("KULLANICI_ADI" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."YONETICI" MODIFY ("SIFRE" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."YONETICI" ADD CONSTRAINT "YONETICI_PK" PRIMARY KEY ("YONETICI_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HABIBOI"."YONETICI" MODIFY ("BOLGE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table OTOMAT
--------------------------------------------------------

  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("OTOMAT_NO" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("IL" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("ILCE" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("MAHALLE" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("SOKAK" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("RAF_KAPASITESI" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("URUN_0" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("URUN_1" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("URUN_2" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."OTOMAT" ADD CONSTRAINT "OTOMAT_PK" PRIMARY KEY ("OTOMAT_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HABIBOI"."OTOMAT" MODIFY ("BAKIM" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CALISAN
--------------------------------------------------------

  ALTER TABLE "HABIBOI"."CALISAN" MODIFY ("CALISAN_NO" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."CALISAN" MODIFY ("AD_SOYAD" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."CALISAN" MODIFY ("EKIP_NO" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."CALISAN" MODIFY ("MUSAITLIK" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."CALISAN" ADD CONSTRAINT "EKIP_CALISANI_PK" PRIMARY KEY ("CALISAN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "HABIBOI"."CALISAN" MODIFY ("KULLANICI_ADI" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."CALISAN" MODIFY ("SIFRE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table URUN
--------------------------------------------------------

  ALTER TABLE "HABIBOI"."URUN" MODIFY ("URUN_NO" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."URUN" MODIFY ("URUN_AD" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."URUN" MODIFY ("FIYAT" NOT NULL ENABLE);
  ALTER TABLE "HABIBOI"."URUN" ADD CONSTRAINT "URUN_PK" PRIMARY KEY ("URUN_NO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
